CREATE DATABASE CERVEJARIA
/*
	RECEITAS
	INSUMOS
	FORNECEDORES
	CLIENTES
	ENDERECOS
	CONTATOS
	USUARIOS TODO: AJUSTAR USUARIOS PARA FUTURO LOGIN
*/

CREATE TABLE USUARIOS
(
	ID INT NOT NULL,
	NOME NVARCHAR(100) NULL,
	CNPJ NVARCHAR(100) NULL,
	IE NVARCHAR(100) NULL,
	ENDERECOID INT NULL,
	TIPO SMALLINT NOT NULL,
	CONSTRAINT [PK_USUARIO_ID] PRIMARY KEY CLUSTERED (ID ASC),
)

CREATE TABLE RECEITAS
(
	ID INT NOT NULL,
	NOME NVARCHAR(100) NULL,
	DESCRICAO NVARCHAR(100) NULL,
	USUARIOID INT NOT NULL,
	CONSTRAINT [PK_RECEITA_ID] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_USUARIORECEITA_ID] FOREIGN KEY (USUARIOID) REFERENCES USUARIOS (ID) ON DELETE CASCADE
)

CREATE TABLE INSUMOS
(
	ID INT NOT NULL,
	NOME NVARCHAR(100) NULL,
	DATACOMPRA DATETIME2 NULL,
	DATAVALIDADE DATETIME2 NULL,
	PRECO DECIMAL(5,0) NULL,
	UNIDADEMED NVARCHAR(100) NULL,
	USUARIOID INT NOT NULL,
	RECEITAID INT NULL
	CONSTRAINT [PK_INSUMO_ID] PRIMARY KEY CLUSTERED (ID ASC),
)
CREATE TABLE RECEITAINSUMO
(
	RECEITAID INT NOT NULL,
	INSUMOID INT NOT NULL,
	CONSTRAINT [PK_RECEITAID_ID] PRIMARY KEY CLUSTERED (RECEITAID ASC, INSUMOID ASC),
	CONSTRAINT [FK_RECEITAINSUMO_ID] FOREIGN KEY (RECEITAID) REFERENCES RECEITAS (ID) ON DELETE CASCADE,
	CONSTRAINT [FK_INSUMORECEITA_ID] FOREIGN KEY (INSUMOID) REFERENCES INSUMOS (ID) ON DELETE CASCADE
)


CREATE TABLE CONTATOS
(
	ID INT NOT NULL,
	TIPO SMALLINT NOT NULL,
	DESCRICAO NVARCHAR(100) NULL,
	USUARIOID INT NOT NULL,
	CONSTRAINT [PK_CONTATO_ID] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_USUARIOCONTATO_ID] FOREIGN KEY (USUARIOID) REFERENCES USUARIOS (ID) ON DELETE CASCADE
)

CREATE TABLE ENDERECOS
(
	ID INT NOT NULL,
	CEP NVARCHAR(100) NULL,
	NOME NVARCHAR(100) NULL,
	TIPO SMALLINT NULL,
	COMPLEMENTO NVARCHAR(100) NULL,
	BAIRRO NVARCHAR(100) NULL,
	CIDADE NVARCHAR(100) NULL,
	UF CHAR(2) NULL,
	PAIS NVARCHAR(100) NULL,
	USUARIOID INT NOT NULL,
	CONSTRAINT [PK_ENDERECO_ID] PRIMARY KEY CLUSTERED (ID ASC),
	CONSTRAINT [FK_USUARIOENDERECO_ID] FOREIGN KEY (USUARIOID) REFERENCES USUARIOS (ID) ON DELETE CASCADE
)